# Translates a system's shell environment (PATH + variables) into a nushell
# "vendor autoload" config.
#
# nix-darwin and NixOS only set PATH/variables for POSIX shells (zsh/bash/fish);
# nushell can't source those. This generates an equivalent .nu file that the
# callers drop into one of nushell's vendor autoload directories:
#   - macOS: profiles/darwin/nushell.nix
#   - Linux: profiles/home/default.nix
#
# Vendor autoloads run *after* the user's config.nu, so the output is
# non-destructive: scalars are only set when unset, and PATH is merged (nix and
# system entries added, duplicates dropped) rather than replaced.
#
# Usage: import ./nushell-vendor.nix { inherit lib pkgs; } { platform; environment; }
#   platform:    "darwin" or "nixos" (the two model the environment differently)
#   environment: the corresponding config.environment
{
  lib,
  pkgs,
}: {
  platform,
  environment,
}: let
  inherit (environment) profiles variables;

  # $HOME/$USER/${XDG_STATE_HOME} are placeholders a POSIX shell would expand;
  # translate them to nushell interpolation. XDG_STATE_HOME is seeded below.
  toNu =
    builtins.replaceStrings ["$HOME" "$USER" "\${XDG_STATE_HOME}"]
    ["($env.HOME)" "($env.USER)" "($env.XDG_STATE_HOME)"];
  nuStr = v: ''$"${toNu v}"'';
  nuList = entries: "[\n${lib.concatMapStringsSep "\n" (p: "      ${nuStr p}") entries}\n    ]";

  # Expand a profile-relative variable ([suffix] -> profile ++ suffix for every
  # profile), the way NixOS's environment.profileRelativeEnvVars works.
  expandProfiles = suffixes: lib.concatMap (p: map (s: p + s) suffixes) profiles;

  # Per-platform PATH split and variable set (the two model the env differently).
  byPlatform =
    if platform == "darwin"
    then rec {
      # nix-darwin bakes the whole PATH into environment.systemPath: nix profile
      # bins followed by the fixed macOS system paths. Split so nix wins over
      # whatever launchd inherited, while the system paths stay as a fallback.
      systemPaths = ["/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin"];
      entries = lib.filter (s: s != "") (lib.splitString ":" environment.systemPath);
      prependPaths = lib.filter (p: !(lib.elem p systemPaths)) entries;
      appendPaths = lib.filter (p: lib.elem p systemPaths) entries;
      scalarVars = variables;
      preludeLines = [];
    }
    else rec {
      # NixOS builds PATH from environment.profiles and profileRelativeEnvVars,
      # prefixed by /run/wrappers/bin (sudo etc., set in environment.extraInit).
      prependPaths = ["/run/wrappers/bin"] ++ expandProfiles (environment.profileRelativeEnvVars.PATH or ["/bin"]);
      appendPaths = [];
      # Merge absolute (environment.variables) and profile-relative variables,
      # absolute first, matching NixOS's set-environment.
      suffixedVars = lib.mapAttrs (_: expandProfiles) (removeAttrs environment.profileRelativeEnvVars ["PATH"]);
      scalarVars =
        lib.zipAttrsWith
        (_: parts: lib.concatStringsSep ":" (lib.filter (s: s != "") (lib.flatten parts)))
        [variables suffixedVars];
      preludeLines = [''$env.XDG_STATE_HOME = ($env.XDG_STATE_HOME? | default $"($env.HOME)/.local/state")''];
    };
  inherit (byPlatform) prependPaths appendPaths scalarVars preludeLines;

  # NIX_PROFILES/NIX_USER_PROFILE_DIR come from environment.extraInit on both.
  vars =
    scalarVars
    // {
      NIX_USER_PROFILE_DIR = "/nix/var/nix/profiles/per-user/$USER";
      NIX_PROFILES = lib.concatStringsSep " " (lib.reverseList profiles);
    };
  varLines =
    lib.concatStringsSep "\n"
    (lib.mapAttrsToList (n: v: "$env.${n} = ($env.${n}? | default ${nuStr v})") vars);

  pathPipeline = lib.concatStringsSep "\n      " (
    ["$env.PATH? | default []"]
    ++ lib.optional (prependPaths != []) "| prepend ${nuList prependPaths}"
    ++ lib.optional (appendPaths != []) "| append ${nuList appendPaths}"
    ++ ["| uniq"]
  );
in
  pkgs.writeText "nushell-${platform}-env.nu" ''
    # Generated by profiles/nushell-vendor.nix -- do not edit.
    # Base environment for nushell, injected from the ${platform} system config.
    ${lib.concatStringsSep "\n" preludeLines}

    ${varLines}

    $env.PATH = (
      ${pathPipeline}
    )
  ''
