name: "Update lock file"
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a GitHub App token
        uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Git author
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'noreply@github.com'

      - name: Update lock file
        run: nix flake update --commit-lock-file

      # - name: Get commit message
      #   id: commit
      #   run: |
      #     delimiter="$(openssl rand -hex 16)"
      #     echo "message<<${delimiter}" >> "${GITHUB_OUTPUT}"
      #     git log -1 --pretty=%B >> "${GITHUB_OUTPUT}"
      #     echo "${delimiter}" >> "${GITHUB_OUTPUT}"

      #     delimiter="$(openssl rand -hex 16)"
      #     echo "pr<<${delimiter}" >> "${GITHUB_OUTPUT}"
      #     git log -1 --pretty=%B | tail +3 | awk -f ./.github/flake-to-markdown.awk >> "${GITHUB_OUTPUT}"
      #     echo "${delimiter}" >> "${GITHUB_OUTPUT}"

      - name: Push to main
        run: |
          git push origin main
